
DEPARTMENTS = (			
			('NEPA', 'NEPA'),
			('Air/Noise', 'Air/Noise'),
			('Archaeology', 'Archaeology'),
			('Aquatics', 'Aquatics'),
			('Ecology', 'Ecology'),			
			('History', 'History'),
			('Survey', 'Survey'),
			('Employee', 'Employee'),
	)

EMPLOYEES = (
			('Adair, David', 'Adair, David'),
			('Barnett, James', 'Barnett, James'),
			('Batt, Brandon', 'Batt, Brandon'),
			('Blackwelder, Jon', 'Blackwelder, Jon'),
			('Brown, Jill', 'Brown, Jill'),
			('Brown, Leslie', 'Brown, Leslie'),
			('Carbo, Andrew', 'Carbo, Andrew'),
			('Cochran, Kendall', 'Cochran, Kendall'),
			('Cook, Ryan', 'Cook, Ryan'),
			('Corcoran, Jennifer', 'Corcoran, Jennifer'),
			('Crawford, Lisa', 'Crawford, Lisa'),
			('Danser, Russ', 'Danser, Russ'),
			('Earhart, Josh', 'Earhart, Josh'),
			('Edwards, Linda', 'Edwards, Linda'),
			('Estes, Charlotte', 'Estes, Charlotte'),
			('Ferrall-Graff, Katheryn', 'Ferrall-Graff, Katheryn'),
			('Filer, Rick', 'Filer, Rick'),
			('Glen, Casey', 'Glen, Casey'),
			('Green, Lillian', 'Green, Lillian'),
			('Grindstaff, Mark', 'Grindstaff, Marc'),
			('Hudson, Grant', 'Hudson, Grant'),
			('Hunt, Mike', 'Hunt, Mike'),
			('Jordan, Stephanie', 'Jordan, Stephanie'),
			('Lane, Collin', 'Lane, Collin'),
			('Melville, Martin', 'Melville, Martin'),
			('Moss, Richard', 'Moss, Richard'),
			('Niccoli, Morgan', 'Niccoli, Morgan'),
			('Niccoli, Ryan', 'Niccoli, Ryan'),
			('Pearce, David', 'Pearce, David'),
			('Perrin, Heather', 'Perrin, Heather'),
			('Pietak, Lynn', 'Pietak, Lynn'),
			# ('Pitman, Andy', 'Pitman, Andy'),
			('Quirk, Phillip', 'Quirk, Phillip'),
			('Roberts, Joseph', 'Roberts, Joseph'),
			('Teall, Martha', 'Teall, Martha'),
			# ('Theos, Nick', 'Theos, Nick'),
			('Thomas, Kevin', 'Thomas, Kevin'),
			('Thomas, Susan', 'Thomas, Susan'),
			('Trudeau, Mary', 'Trudeau, Mary'),
			('Welch, Lauren', 'Welch, Lauren'),
			# ('Winkles, Debbie', 'Winkles, Debbie'),
		)

PROJECT_MANAGERS = (
			('Susan Thomas', 'Susan Thomas'),
			('Heather Perrin', 'Heather Perrin'),
			('Josh Earhart', 'Josh Earhart'),
			('Russ Danser', 'Russ Danser'),
			('Jill Brown', 'Jill Brown'),
			('Jim Woodson', 'Jim Woodson'),
			('Mark Grindstaff', 'Mark Grindstaff'),
			('Dave Pierce', 'Dave Pierce')
	)

NEPA_PLANNERS = (
			('Susan Thomas', 'Susan Thomas'),
			('Heather Perrin', 'Heather Perrin'),
			('Josh Earhart', 'Josh Earhart'),
			('Russ Danser', 'Russ Danser'),
			('Jill Brown', 'Jill Brown'),
			('Jim Woodson', 'Jim Woodson'),
	)

CLIENTS = (
			('Heath and Lineback', 'Heath and Lineback'),
			('Parsons Brinkerhoff', 'Parsons Brinkerhoff'),
			('Kimley-Horn', 'Kimley-Horn'),
			('HTB', 'HTB'),
			('Arcadis', 'Arcadis'),
			('HDR', 'HDR'),
	)

COUNTIES = {'Appling':5, 'Atkinson':4, 'Bacon':5, 'Baker':4, 'Baldwin':2,
'Banks':1, 'Barrow':1, 'Bartow':6, 'Ben Hill':4, 'Berrien':4, 'Bibb':3,
'Bleckley':2, 'Brantley':5, 'Brooks':4, 'Bryan':5,
'Bulloch':5, 'Burke':2, 'Butts':3, 'Calhoun':4,
'Camden':5, 'Candler':5, 'Carroll':6, 'Catoosa':6,
'Charlton':5,'Chatham':5, 'Chattahoochee':3, 'Chattooga':6,
'Cherokee':6, 'Clarke':1, 'Clay':4, 'Clayton':7,
'Clinch':4, 'Cobb':7, 'Coffee':4, 'Colquitt':4,
'Columbia':2, 'Cook':4, 'Coweta':3, 'Crawford':3,
'Crisp':4, 'Dade':6, 'Dawson':1, 'Decatur':4,
'DeKalb':7, 'Dodge':2, 'Dooly':3, 'Dougherty':4,
'Douglas':7, 'Early':4, 'Echols':4, 'Effingham':5,
'Elbert':1, 'Emanuel':2, 'Evans':5, 'Fannin':6,
'Fayette':3, 'Floyd':6, 'Forsyth':1, 'Franklin':1,
'Fulton':7, 'Gilmer':6, 'Glascock':2, 'Glynn':5,
'Gordon':6, 'Grady':4, 'Greene':2,'Gwinnett':1,
'Habersham':1, 'Hall':1, 'Hancock':2, 'Haralson':6,
'Harris':3, 'Hart':1, 'Heard':3, 'Henry':3,
'Houston':3, 'Irwin':4, 'Jackson':1, 'Jasper':2,
'Jeff Davis':5, 'Jefferson':2, 'Jenkins':2, 'Johnson':2,
'Jones':3, 'Lamar':3, 'Lanier':4, 'Laurens':2,
'Lee':4, 'Liberty':5, 'Lincoln':2, 'Long':5,
'Lowndes':4, 'Lumpkin':1, 'McDuffie':2, 'McIntosh':5,
'Macon':3, 'Madison':1, 'Marion':3, 'Meriwether':3,
'Miller':4, 'Mitchell':4, 'Monroe':3, 'Montgomery':5,
'Morgan':2, 'Murray':6, 'Muscogee':3, 'Newton':2,
'Oconee':1, 'Oglethorpe':2, 'Paulding':6, 'Peach':3,
'Pickens':6, 'Pierce':5, 'Pike':3, 'Polk':6,
'Pulaski':3, 'Putnam':2, 'Quitman':4, 'Rabun':1,
'Randolph':4, 'Richmond':2, 'Rockdale':7, 'Schley':3,
'Screven':2, 'Seminole':4, 'Spalding':3, 'Stephens':1,
'Stewart':3, 'Sumter':3, 'Talbot':3, 'Taliaferro':2,
'Tattnall':5, 'Taylor':3, 'Telfair':5, 'Terrell':4,
'Thomas':4, 'Tift':4, 'Toombs':5, 'Towns':1,
'Treutlen':2, 'Troup':3,'Turner':4, 'Twiggs':3,
'Union':1, 'Upson':3, 'Walker':6, 'Walton':1,
'Ware':5, 'Warren':2, 'Washington':2, 'Wayne':5,
'Webster':3, 'Wheeler':5, 'White':1, 'Whitfield':6,
'Wilcox':4, 'Wilkes':2, 'Wilkinson':2, 'Worth':4,
}

COUNTY_NAMES = [(c, c) for c in sorted(COUNTIES.iterkeys())]

ENVIRONMENTAL_DOCUMENTS = (
 				('CE', 'CE'),
				('EA', 'EA'),
				('EIS', 'EIS'),
				('FONSI', 'FONSI'),
				('GEPA_Type_B', 'GEPA Type B'),
				('GEPA_EER', 'GEPA EER'),
				)

DOCUMENT_TYPES = (
				('PM25', 'PM25'),
				('GEPA', 'GEPA'),
				('Air Assessment', 'Air Assessment'),
				('Air Memorandum', 'Air Memorandum'),
				)