language: python
python:
    - "2.7"
install: 
    - "pip install -r requirements.txt"
services: postgresql
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
script: 
    - "python manage.py test --settings=eptrack.settings_development"